language: r
cache: packages
sudo: false
cache: packages
r:
  - release
  - devel

addons:
  apt:
    packages:
      - libudunits2-dev

r_packages:
  - covr
      
after_success:
  - Rscript -e 'library(covr); codecov()'
